// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:CSharpUtils.MarketData.RandomPriceBarsDataSource.EmulateDateGap(System.DateTime)~System.DateTime")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:CSharpUtils.MarketData.RandomPriceBarsDataSource.GetNextData~CSharpUtils.MarketData.PriceBar")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:CSharpUtils.MarketData.RandomPriceBarsDataSource.GetNextRandomPriceBar~CSharpUtils.MarketData.PriceBar")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0105:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:CSharpUtils.MarketData.RandomPriceBarsDataSource.GetNextRandomPriceBar~CSharpUtils.MarketData.PriceBar")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0105:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:CSharpUtils.MarketData.RandomPriceBarsDataSource.GetUpdatedData~CSharpUtils.MarketData.PriceBar")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:CSharpUtils.MarketData.RandomPriceBarsDataSource.OnTimerElapsed")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:CSharpUtils.MarketData.DataManager.ComputeMovingAverage(System.Collections.Generic.IList{System.Double},System.Int32)~System.Collections.Generic.IList{System.Double}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:CSharpUtils.MarketData.DataManager.GenerateEEG(System.Int32,System.Double@,System.Double)~CSharpUtils.MarketData.DoubleSeries")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:CSharpUtils.MarketData.DataManager.GenerateSpiral(System.Double,System.Double,System.Double,System.Int32)~CSharpUtils.MarketData.DoubleSeries")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1059:Avoid locking on publicly accessible instance.", Justification = "<Pending>", Scope = "member", Target = "~M:CSharpUtils.MarketData.DataManager.GetAvailableTimeFrames(CSharpUtils.Common.Instrument)~System.Collections.Generic.IEnumerable{CSharpUtils.Common.TimeFrame}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:CSharpUtils.MarketData.DataManager.GetButterflyCurve(System.Int32)~CSharpUtils.MarketData.DoubleSeries")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:CSharpUtils.MarketData.DataManager.GetDampedSinewave(System.Int32,System.Double,System.Double,System.Double,System.Int32,System.Int32)~CSharpUtils.MarketData.DoubleSeries")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:CSharpUtils.MarketData.DataManager.GetExponentialCurve(System.Double,System.Int32)~CSharpUtils.MarketData.DoubleSeries")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:CSharpUtils.MarketData.DataManager.GetLissajousCurve(System.Double,System.Double,System.Double,System.Int32)~CSharpUtils.MarketData.DoubleSeries")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:CSharpUtils.MarketData.DataManager.GetStraightLine(System.Double,System.Double,System.Int32)~CSharpUtils.MarketData.DoubleSeries")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:CSharpUtils.MarketData.DataManager.GetSubstring(System.String,System.String,System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:CSharpUtils.MarketData.DataManager.Offset(System.Collections.Generic.IList{System.Double},System.Double)~System.Collections.Generic.IEnumerable{System.Double}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1059:Avoid locking on publicly accessible instance.", Justification = "<Pending>", Scope = "member", Target = "~P:CSharpUtils.MarketData.DataManager.AvailableInstruments")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2002:DoNotLockOnObjectsWithWeakIdentity", Scope = "member", Target = "CSharpUtils.MarketData.DataManager.#AvailableInstruments")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2002:DoNotLockOnObjectsWithWeakIdentity", Scope = "member", Target = "CSharpUtils.MarketData.DataManager.#GetAvailableTimeFrames(CSharpUtils.Common.Instrument)")]

